### PR TITLE
Fix build with kernel 6.6

### LINKED ISSUE #15: build fails with linux 6.6
```
  CC [M]  /home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_pci_common.o
/home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_vmmci.c:94:10: error: 'struct ctl_table' has no member named 'child'
   94 |         .child          = drift_table,
      |          ^~~~~
/home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_vmmci.c:94:27: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
   94 |         .child          = drift_table,
      |                           ^~~~~~~~~~~
/home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_vmmci.c:94:27: note: (near initialization for 'vmmci_table')
/home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_vmmci.c: In function 'vmmci_probe':
/home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_vmmci.c:285:30: error: implicit declaration of function 'register_sysctl_table'; did you mean 'unregister_sysctl_table'? [-Werror=implicit-function-declaration]
  285 |         vmmci_table_header = register_sysctl_table(&vmmci_table);
      |                              ^~~~~~~~~~~~~~~~~~~~~
      |                              unregister_sysctl_table
/home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_vmmci.c:285:28: warning: assignment to 'struct ctl_table_header *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  285 |         vmmci_table_header = register_sysctl_table(&vmmci_table);
      |                            ^
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /home/ncopa/aports/community/virtio_vmmci-lts/src/lts/virtio_vmmci.o] Error 1
```

### PR DESCRIPTION
**Pull request by ncopa**
The deprecated child node was replaced with an enum in commit 2f2665c13af (sysctl: replace child with an enumeration)

fixes: https://github.com/voutilad/virtio_vmmci/issues/15
ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit?id=2f2665c13af4895b26761107c2f637c2f112d8e9kl

### CODE REVIEW

**Comment by voutilad** [comment]
Thanks. Just seeing this now, but I've already made a commit that should fix newer kernels and keep support for older.
